ARG container_version=20.04
FROM ubuntu:${container_version}

LABEL author="Nicola Spallanzani - nicola.spallanzani@nano.cnr.it - S3 centre, CNR-NANO"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -yqq update \
 && apt-get -yqq install --no-install-recommends \
        build-essential ca-certificates curl file \
        make cmake gcc g++ gfortran \
        git gnupg2 iproute2 lmod locales lua-posix \
        python2 python3 python3-pip python3-setuptools \
        tcl unzip m4 wget git zlib1g-dev ssh \
 && apt-get clean \
 && locale-gen en_US.UTF-8 \
 && pip3 install boto3

ENV SPACK_ROOT=/opt/spack \
    PATH=/opt/spack/bin:$PATH

RUN cd /opt && git clone https://github.com/nicspalla/my-repo.git \
 && git clone https://github.com/spack/spack.git \
 && cd spack && git checkout releases/v0.18 && . share/spack/setup-env.sh \
 && printf "repos:\n  - /opt/my-repo\n  - $SPACK_ROOT/var/spack/repos/builtin\n" > $SPACK_ROOT/etc/spack/defaults/repos.yaml \
 && spack compiler find --scope site && spack external find --scope site \
 && spack install gcc@12.1.0 && spack compiler add --scope site $(spack location -i gcc@12.1.0) \
 && spack install yambo@5.1.1%gcc@12.1.0 +mpi +openmp +ph +rt +sc +nl profile=time,memory linalg=slepc \
 && spack clean --stage && spack clean -a && spack clean --downloads && spack clean --misc-cache

WORKDIR /scratch

RUN . $SPACK_ROOT/share/spack/setup-env.sh && spack load yambo \
 && echo "PATH=$PATH" >> ${SPACK_ROOT}/env.txt \
 && echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> ${SPACK_ROOT}/env.txt 

RUN adduser --disabled-password yambo
USER yambo
